version: 0.0

phases:
  pre_build:
    commands:
      - echo Build started on `date`
      - mvn install:install-file -Dfile=./src/main/resources/ojdbc7-11.2.0jar -DgroupId=com.oracle -DartifactId=ojdbc7 -Dversion=11.2.0 -Dpackaging=jar
      - mvn test
  build:
    commands:
      - echo Build completed on `date`
      - mvn clean package
      - mv target/Takoot-Back-0.0.1-SNAPSHOT.war Takoot-Back-0.0.1-SNAPSHOT.war
artifacts:
  files:
    - Takoot-Back-0.0.1-SNAPSHOT.war
    - .ebextensions/**/*